#include <systemlib/param/param.h>

PARAM_DEFINE_FLOAT(IMU_GYO_SCAL_X, 1.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_SCAL_Y, 1.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_SCAL_Z, 1.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_BIAS_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_BIAS_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_BIAS_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_BIAS1_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_BIAS1_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_BIAS1_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_BIAS2_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_BIAS2_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_BIAS2_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_BIAS3_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_BIAS3_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_BIAS3_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_ALGN_XY, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_ALGN_XZ, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_ALGN_YX, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_ALGN_YZ, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_ALGN_ZX, 0.0f);
PARAM_DEFINE_FLOAT(IMU_GYO_ALGN_ZY, 0.0f);

/* accel offsets */
PARAM_DEFINE_FLOAT(IMU_ACC_SCAL_X, 1.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_SCAL_Y, 1.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_SCAL_Z, 1.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_SCAL1_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_SCAL1_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_SCAL1_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_SCAL2_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_SCAL2_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_SCAL2_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_SCAL3_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_SCAL3_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_SCAL3_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_BIAS_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_BIAS_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_BIAS_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_BIAS1_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_BIAS1_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_BIAS1_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_BIAS2_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_BIAS2_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_BIAS2_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_BIAS3_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_BIAS3_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_BIAS3_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_ALGN_XY, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_ALGN_XZ, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_ALGN_YX, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_ALGN_YZ, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_ALGN_ZX, 0.0f);
PARAM_DEFINE_FLOAT(IMU_ACC_ALGN_ZY, 0.0f);

/* accel offsets */
PARAM_DEFINE_FLOAT(IMU_MAG_SCAL_X, 1.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_SCAL_Y, 1.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_SCAL_Z, 1.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_SCAL1_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_SCAL1_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_SCAL1_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_SCAL2_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_SCAL2_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_SCAL2_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_SCAL3_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_SCAL3_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_SCAL3_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_BIAS_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_BIAS_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_BIAS_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_BIAS1_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_BIAS1_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_BIAS1_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_BIAS2_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_BIAS2_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_BIAS2_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_BIAS3_X, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_BIAS3_Y, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_BIAS3_Z, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_ALGN_XY, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_ALGN_XZ, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_ALGN_YX, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_ALGN_YZ, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_ALGN_ZX, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_ALGN_ZY, 0.0f);
PARAM_DEFINE_FLOAT(IMU_MAG_INCL,-64.0f);


PARAM_DEFINE_INT32(SENS_DPRES_OFF, 1667);

PARAM_DEFINE_FLOAT(RC1_MIN, 1000.0f);
PARAM_DEFINE_FLOAT(RC1_TRIM, 1500.0f);
PARAM_DEFINE_FLOAT(RC1_MAX, 2000.0f);
PARAM_DEFINE_FLOAT(RC1_REV, 1.0f);
PARAM_DEFINE_FLOAT(RC1_DZ, 0.0f);

PARAM_DEFINE_FLOAT(RC2_MIN, 1000);
PARAM_DEFINE_FLOAT(RC2_TRIM, 1500);
PARAM_DEFINE_FLOAT(RC2_MAX, 2000);
PARAM_DEFINE_FLOAT(RC2_REV, 1.0f);
PARAM_DEFINE_FLOAT(RC2_DZ, 0.0f);

PARAM_DEFINE_FLOAT(RC3_MIN, 1000);
PARAM_DEFINE_FLOAT(RC3_TRIM, 1500);
PARAM_DEFINE_FLOAT(RC3_MAX, 2000);
PARAM_DEFINE_FLOAT(RC3_REV, 1.0f);
PARAM_DEFINE_FLOAT(RC3_DZ, 0.0f);

PARAM_DEFINE_FLOAT(RC4_MIN, 1000);
PARAM_DEFINE_FLOAT(RC4_TRIM, 1500);
PARAM_DEFINE_FLOAT(RC4_MAX, 2000);
PARAM_DEFINE_FLOAT(RC4_REV, 1.0f);
PARAM_DEFINE_FLOAT(RC4_DZ, 30.0f);

PARAM_DEFINE_FLOAT(RC5_MIN, 1000);
PARAM_DEFINE_FLOAT(RC5_TRIM, 1500);
PARAM_DEFINE_FLOAT(RC5_MAX, 2000);
PARAM_DEFINE_FLOAT(RC5_REV, 1.0f);
PARAM_DEFINE_FLOAT(RC5_DZ,  0.0f);

PARAM_DEFINE_FLOAT(RC6_MIN, 1000);
PARAM_DEFINE_FLOAT(RC6_TRIM, 1500);
PARAM_DEFINE_FLOAT(RC6_MAX, 2000);
PARAM_DEFINE_FLOAT(RC6_REV, 1.0f);
PARAM_DEFINE_FLOAT(RC6_DZ, 0.0f);

PARAM_DEFINE_FLOAT(RC7_MIN, 1000);
PARAM_DEFINE_FLOAT(RC7_TRIM, 1500);
PARAM_DEFINE_FLOAT(RC7_MAX, 2000);
PARAM_DEFINE_FLOAT(RC7_REV, 1.0f);
PARAM_DEFINE_FLOAT(RC7_DZ, 0.0f);

PARAM_DEFINE_FLOAT(RC8_MIN, 1000);
PARAM_DEFINE_FLOAT(RC8_TRIM, 1500);
PARAM_DEFINE_FLOAT(RC8_MAX, 2000);
PARAM_DEFINE_FLOAT(RC8_REV, 1.0f);
PARAM_DEFINE_FLOAT(RC8_DZ, 0.0f);

PARAM_DEFINE_FLOAT(RC9_MIN, 1000);
PARAM_DEFINE_FLOAT(RC9_TRIM, 1500);
PARAM_DEFINE_FLOAT(RC9_MAX, 2000);
PARAM_DEFINE_FLOAT(RC9_REV, 1.0f);
PARAM_DEFINE_FLOAT(RC9_DZ, 0.0f);

PARAM_DEFINE_FLOAT(RC10_MIN, 1000);
PARAM_DEFINE_FLOAT(RC10_TRIM, 1500);
PARAM_DEFINE_FLOAT(RC10_MAX, 2000);
PARAM_DEFINE_FLOAT(RC10_REV, 1.0f);
PARAM_DEFINE_FLOAT(RC10_DZ, 0.0f);

PARAM_DEFINE_FLOAT(RC11_MIN, 1000);
PARAM_DEFINE_FLOAT(RC11_TRIM, 1500);
PARAM_DEFINE_FLOAT(RC11_MAX, 2000);
PARAM_DEFINE_FLOAT(RC11_REV, 1.0f);
PARAM_DEFINE_FLOAT(RC11_DZ, 0.0f);

PARAM_DEFINE_FLOAT(RC12_MIN, 1000);
PARAM_DEFINE_FLOAT(RC12_TRIM, 1500);
PARAM_DEFINE_FLOAT(RC12_MAX, 2000);
PARAM_DEFINE_FLOAT(RC12_REV, 1.0f);
PARAM_DEFINE_FLOAT(RC12_DZ, 0.0f);

PARAM_DEFINE_FLOAT(RC13_MIN, 1000);
PARAM_DEFINE_FLOAT(RC13_TRIM, 1500);
PARAM_DEFINE_FLOAT(RC13_MAX, 2000);
PARAM_DEFINE_FLOAT(RC13_REV, 1.0f);
PARAM_DEFINE_FLOAT(RC13_DZ, 0.0f);

PARAM_DEFINE_FLOAT(RC14_MIN, 1000);
PARAM_DEFINE_FLOAT(RC14_TRIM, 1500);
PARAM_DEFINE_FLOAT(RC14_MAX, 2000);
PARAM_DEFINE_FLOAT(RC14_REV, 1.0f);
PARAM_DEFINE_FLOAT(RC14_DZ, 0.0f);

PARAM_DEFINE_INT32(RC_TYPE, 1); /** 1 = FUTABA, 2 = Spektrum, 3 = Graupner HoTT, 4 = Turnigy 9x */

/* default is conversion factor for the PX4IO / PX4IOAR board, the factor for PX4FMU standalone is different */
PARAM_DEFINE_FLOAT(BAT_V_SCALING, (3.3f * 52.0f / 5.0f / 4095.0f));

PARAM_DEFINE_INT32(RC_MAP_ROLL, 1);
PARAM_DEFINE_INT32(RC_MAP_PITCH, 2);
PARAM_DEFINE_INT32(RC_MAP_THROTTLE, 3);
PARAM_DEFINE_INT32(RC_MAP_YAW, 4);

PARAM_DEFINE_INT32(RC_MAP_OVER_SW, 5);
PARAM_DEFINE_INT32(RC_MAP_MODE_SW, 6);

PARAM_DEFINE_INT32(RC_MAP_MAN_SW, 0);
PARAM_DEFINE_INT32(RC_MAP_SAS_SW, 0);
PARAM_DEFINE_INT32(RC_MAP_RTL_SW, 0);
PARAM_DEFINE_INT32(RC_MAP_OFFB_SW, 0);

PARAM_DEFINE_INT32(RC_MAP_FLAPS, 0);

PARAM_DEFINE_INT32(RC_MAP_AUX1, 0);	/**< default function: camera yaw / azimuth */
PARAM_DEFINE_INT32(RC_MAP_AUX2, 0);	/**< default function: camera pitch / tilt */
PARAM_DEFINE_INT32(RC_MAP_AUX3, 0);	/**< default function: camera trigger */
PARAM_DEFINE_INT32(RC_MAP_AUX4, 0);	/**< default function: camera roll */
PARAM_DEFINE_INT32(RC_MAP_AUX5, 0);	/**< default function: payload drop */

PARAM_DEFINE_FLOAT(RC_SCALE_ROLL, 0.4f);
PARAM_DEFINE_FLOAT(RC_SCALE_PITCH, 0.4f);
PARAM_DEFINE_FLOAT(RC_SCALE_YAW, 1.0f);
